### ISSUE TITLE
How do I get neofetch girl to display without losing resolution?

### ISSUE THREAD

**Issue by comiluv** [kiedtl/winfetch#100]
Environment: Windows Terminal 1.9.1942.0
I've installed winfetch and while fiddling around with it, I thought the [default picture](https://camo.githubusercontent.com/82b03feab20083a17944229ea151c0fbd521cae0ecb44a8b2f3934ebce2e1e91/68747470733a2f2f692e696d6775722e636f6d2f47466d433541642e706e67) in [neofetch](https://github.com/dylanaraps/neofetch) is quite nice and wanted her on my terminal.

So I downloaded and saved the picture as a png file, cropped out extra stuffs except the girl, but when I loaded the image, the image was awfully low-res compared to the screenshot on the neofetch github page. [Imgur](https://imgur.com/AppIt7b)

How do I get that girl on my terminal without losing any resolution, like shown in the neofetch page? Thank you.

**Comment by rashil2000** [comment]
Inline terminal images are not supported by winfetch at the moment. This is largely a limitation of the terminal, because there aren't any terminals on Windows (with the notable exception of mintty) that can show inline images. Windows Terminal has issues logged requesting this feature, but they don't have plans for it anytime soon.

The current winfetch implementation turns images into a grid of blocks that get approximated to the image.

**Comment by comiluv** [comment]
That's a bummer :( I suppose I won't be seeing the neofetch girl on Windows Terminal anytime soon
